config/routes.rb
Rails.application.routes.draw do
  resources :installations, only: [:create, :show, :destroy]
  
  resources :infrastructures, only: [:index, :show, :create, :destroy]
  resources :fittings, only: [:create, :destroy]

   root to: 'infrastructures#index'
end

app/models/fitting.rb
class Fitting < ActiveRecord::Base
end

app/models/infrastructure.rb
class Infrastructure < ActiveRecord::Base
  has_many :installations, dependent: :destroy
  has_many :fittings, through: :installations

  validates :area, presence: { message: 'Please provide a area' }

end

app/models/installation.rb
class Installation < ActiveRecord::Base
  belongs_to :infrastructure
  belongs_to :fitting

  def total_wattage
    self.fitting.wattage * self.quantity
  end

  # Energy consumption calculation
  # The energy E in kilowatt-hours (kWh) per day is equal to the power P in
  # watts (W) times number of usage hours per day t divided by 1000 watts per
  # kilowatt:
  # E(kWh/day) = P(W) × t(h/day) / 1000(W/kW)
  def total_consumption_per_day
    (total_wattage * running_time) / 1000
  end

  def total_consumption_per_month
    total_consumption_per_day * 30
  end

  def total_consumption_per_year
    total_consumption_per_day * 365
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fittings_controller.rb
class FittingsController < ApplicationController
  # def create
  #   # @fitting = Infrastructure.find(params[:infrastructure_id]).fittings.create(typo: params[:typo])
  #   @fitting = Infrastructure.find(params[:infrastructure_id])..installation.create(name: params[:name])
  # end

  def destroy
    # @fitting = fitting.find(params[:id])
    # @fitting.destroy
  end
end

app/controllers/infrastructures_controller.rb
class InfrastructuresController < ApplicationController
  def index
    @infras = Infrastructure.all
    @infra = Infrastructure.includes(installations: :fitting).first
    @fittings = Fitting.all
  end

  def show
    @Infras = Infrastructure.includes(installations: :fitting).find(params[:id])
  end

  def create
    @Infra = Infrastructure.create(area: params[:area])
    @Infras = Infrastructure.all
  end

  def destroy
    @deleted = Infrastructure.find(params[:id]).destroy
    @infra = Infrastructure.includes(installations: :fitting).first

    render :show
  end
end

app/controllers/installations_controller.rb
class InstallationsController < ApplicationController
  def show
  end

  def create
    @inst = Infrastructure.find(params[:infrastructure_id]).installations.find_by(fitting_id: params[:typo])
    if @inst.present?
      @inst.quantity = params[:quantity]
      @inst.running_time = params[:running_time]
      @inst.save!
    else
      @inst = Infrastructure.find(params[:infrastructure_id]).installations.create(fitting_id: params[:typo], quantity: params[:quantity], running_time: params[:running_time] )
    end
  end

  def destroy
    @inst = Installation.find(params[:id])
    @inst.destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fittings_helper.rb
module FittingsHelper
end

app/helpers/infrastructures_helper.rb
module InfrastructuresHelper
end

app/helpers/installations_helper.rb
module InstallationsHelper
end

app/views/fittings/_fitting.html.slim
div[class="fitting fitting-#{fitting.id}"]

  .time "place holder"

  - if fitting.present?
    = link_to 'delete', fitting, { class: 'fitting-action action-delete', remote: true, method: :delete }

  .fitting-title
    - if fitting.present?
      span.icon &#9874;
    
    span #{fitting.typo}
    span #{fitting.wattage}
    
    
  div[class="fitting-logs logs-#{fitting.id}"]
    / = render fitting.installations

app/views/infrastructures/_infrastructure.html.slim
= link_to infrastructure.area, infrastructures_path(infrastructure), {class: "infrastructure infrastructure-#{infrastructure.id}", remote: true}

app/views/infrastructures/index.html.slim
/ .col-md-4.col-sm-3
/   ul.tabs
/     li
/       = form_tag('/infrastructures', method: :post, remote: true) do
/         = text_field_tag(:area, nil, placeholder: 'New Area')
/         / - binding.pry
/     - @infras.each_with_index do |infra, index|
/       li[class="#{'active' if index == 0}#{' last' if index == @infras.size-1}"]
/         = render infra 
/ 
/   / .infra-fitting = format_fittings(@infra.fittings)
/ 
/     = link_to 'delete infra', infrastructures_path(id: @infra.id, format: 'js'), { class: 'infra-delete', remote: true, method: :delete }
h2.sub-header
  | Add fittings
.installation-createaa
  = form_tag('/installations', method: :post, remote: true, class: "form-horizontal") do
    .from-group
      = label_tag "Type : "
      = select_tag :typo, options_from_collection_for_select(@fittings, :id, :typo, :wattage), include_blank: false, class: "form-control"
      
    .from-group
      = label_tag "Quantity : "
      = select_tag :quantity, options_for_select(("1".."100").to_a, 10), class: "form-control"
    
    .from-group
      = label_tag "Usage hours per day : "
      = select_tag :running_time, options_for_select(("1".."24").to_a, "8"), class: "form-control"
    
    .from-group
      = hidden_field_tag(:infrastructure_id, "#{@infras.empty? ? 0 : @infras.first.id}")
    
    = button_tag "Add", class: "btn btn-default btn-lg active"

h2.sub-header
  | Current installations
- if @infra.present?
  
  table.table.table-bordered.table-hover.table-condensed.rtxt
    thead
      tr.bg-primary
        th #
        th Type
        th Wattage
        th Quantity
        th Hours of use per day
        th Total Wattage
        th Energy consumed per day
        th Energy consumed per month
        th.text-danger Delete
        th.text-warning Edit
      = render @infra.installations
        
- else
  h3.lead.sub-header
    | Please Add Infrastructure

app/views/installations/_installation.html.slim
tbody.tbl[class="tbl-#{installation.fitting.id}"]
  tr.text-center
  - if installation.present?
    td.icon &#9417;
    td.typo = installation.fitting.typo
    td.wattage = installation.fitting.wattage
    td.quantity = installation.quantity
    td.running_time = installation.running_time
    td.total_wattage = installation.total_wattage
    td.consumption_per_day = installation.total_consumption_per_day
    td.consumption_per_month = installation.total_consumption_per_month
    td.delete = link_to 'X', installation, { class: 'installation-action action-delete', remote: true, method: :delete }
    td.edit = link_to 'edit', installation, { class: 'installation-action action-edit', remote: true, method: :edit } 

app/views/installations/show.html.slim
h1 Installations#show
p Find me in app/views/installations/show.html.slim

app/views/layouts/app.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title
      | Citylights
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav
      .navbar.navbar-inverse.navbar-fixed-top
        .container-fluid
          .navbar-header
            button.btn.btn-navbar[type="button" data-toggle="collapse" data-target=".nav-collapse" aria-expanded="false" aria-controls="navbar"]
              span.sr-only
                | Toggle navigation
              span.icon-bar
              span.icon-bar
              span.icon-bar
            a.navbar-brand[href="/"]
              | CityLight
            .nav-collapse.collapse
              ul.nav.navbar-nav.navbar-right
                li
                  a[href="/"]
                    | Home
                li
                  a[href="/"]
                    | About
                li
                  a[href="/"]
                    | Contact
              form.navbar-search.pull-right
                input.search-query[type="text" placeholder="Search"]
    .container
      .row
        = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Citylights</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title
      | Citylights
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-inverse.navbar-fixed-top
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"]
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand[href="/"]
            | CityLight
        .nav-collapse.collapse [id="navbar"]
          ul.nav.navbar-nav.navbar-right
            li
              a[href="/"]
                | Home
            li
              a[href="/"]
                | About
            li
              a[href="/"]
                | Contact
          form.navbar-search.pull-right
            input.search-query[type="text" placeholder="Search"] 
    .container-fluid
      .row
        .col-sm-3.col-md-2.sidebar
      .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
        = yield

app/views/layouts/newapp.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title
      | Citylights
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        container-fluid
          button.btn.btn-navbar[type="button" data-toggle="collapse" data-target=".nav-collapse"]
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand[href="#"] City Light
          .nav-collapse.collapse
            p.navbar-text.pull-right
              | Logged in As
              a.navbar-link[href='#'] 
                | User name
            ul.nav
              li.active
                a[href="/"]
                  | Home
              li
                a[href="/"]
                  | About
              li
                a[href="/"]
                  | Contact
    .container-fluid
      .row-fluid
        span3
          .well.sidebar-nav
            ul.nav.nav-list
              li.nav-header
                | Side Bar
              li.active
                | Link1
              li 
                | Link2
              li 
                | Link3
              li.nav-header
                | Side Bar 2
              li.active
                | Link1
              li 
                | Link2
              li 
                | Link3  
        span9
          .hero-unit
            h1
              | Hello 
            p 
              | This is a  li Lorem ipsum...  li Lorem ipsum...
            p 
              a.btn.btn-primary.btn-large[href="/"] 
          .row-fluid
            span4
              h2  
                | Heading
              p Lorem ipsum...
              p 
                a.btn[href="/"]
                  | view more
                  
                  